version: '3.8'

services:
  web:
    build:
      context: ../..
      dockerfile: docker/production/Dockerfile
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - DB_NAME=employee_tracking
      - DB_USER=django_user
      - DB_PASSWORD=mysecretpassword
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
      - redis

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=employee_tracking
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_user -d employee_tracking"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ../../.env

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume:
  media_volume: